/**
 * Cloudflare Pages Functions Middleware
 * Handles ?agent=true requests for AI agent discovery
 *
 * AGENT_DATA is generated by scripts/prebuild.ts from siteData.ts
 */

import AGENT_DATA from './_generated/agent-data.json';

// Generate navigation page
function generateNavigation() {
  return `<!DOCTYPE html>
<html>
<head><title>Bryson Tang - Agent View</title></head>
<body>
<pre>
BRYSON TANG - STRUCTURED DATA FOR AI AGENTS
============================================

MCP Endpoint (preferred): https://mcp.brysontang.com
Discovery: https://mcp.brysontang.com/.well-known/mcp.json

Available Content Sections:
- https://brysontang.com/?agent=true&content=profile
- https://brysontang.com/?agent=true&content=resume
- https://brysontang.com/?agent=true&content=projects
- https://brysontang.com/?agent=true&content=skills
- https://brysontang.com/?agent=true&content=contact

Current Status: ${AGENT_DATA.profile.status}
Location: ${AGENT_DATA.profile.location}

Quick Summary:
- AI Systems Architect & Research Engineer
- Creator of Synapse (Fast-Weight Architecture) & Agent Tokens Protocol
- Builder of Crystallize (Experimental Framework)
- WPI Data Science (3.75 GPA, High Distinction)
- BlueDot AI Safety Alignment certified

Fetch any section URL above for detailed data.
</pre>
</body>
</html>`;
}

// Generate profile content
function generateProfile() {
  const p = AGENT_DATA.profile;
  return `BRYSON TANG - PROFILE
=====================

Name: ${p.name}
Title: ${p.tagline}
Location: ${p.location}

Status: ${p.status}
Availability: ${p.availability}

Links:
- Website: ${p.links.website}
- GitHub: ${p.links.github}
- LinkedIn: ${p.links.linkedin}
- MCP Endpoint: ${p.links.mcp}

Summary:
${AGENT_DATA.summary}

---
Other sections:
- https://brysontang.com/?agent=true&content=resume
- https://brysontang.com/?agent=true&content=projects
- https://brysontang.com/?agent=true&content=skills
- https://brysontang.com/?agent=true&content=contact
`;
}

// Generate resume content
function generateResume() {
  let output = `BRYSON TANG - RESUME
====================

${AGENT_DATA.profile.name}
${AGENT_DATA.profile.tagline}
${AGENT_DATA.profile.location}

SUMMARY
-------
${AGENT_DATA.summary}

EXPERIENCE
----------
`;

  for (const job of AGENT_DATA.experience) {
    output += `\n${job.role} | ${job.company}\n${job.dates}\n`;
    for (const h of job.highlights) {
      output += `  - ${h}\n`;
    }
  }

  output += `\nEDUCATION
---------
`;
  for (const edu of AGENT_DATA.education) {
    output += `${edu.institution}\n${edu.degree} (${edu.year})\n${edu.details}\n\n`;
  }

  output += `---
Other sections:
- https://brysontang.com/?agent=true&content=profile
- https://brysontang.com/?agent=true&content=projects
- https://brysontang.com/?agent=true&content=skills
- https://brysontang.com/?agent=true&content=contact
`;

  return output;
}

// Generate projects content
function generateProjects() {
  let output = `BRYSON TANG - PROJECTS
======================

`;
  for (const proj of AGENT_DATA.projects) {
    output += `${proj.name}\n${proj.description}\nURL: ${proj.url}\n\n`;
  }

  output += `---
Other sections:
- https://brysontang.com/?agent=true&content=profile
- https://brysontang.com/?agent=true&content=resume
- https://brysontang.com/?agent=true&content=skills
- https://brysontang.com/?agent=true&content=contact
`;

  return output;
}

// Generate skills content
function generateSkills() {
  const s = AGENT_DATA.skills;
  return `BRYSON TANG - SKILLS
====================

Research Interests: ${s.research.join(', ')}

Languages: ${s.languages.join(', ')}

ML/AI: ${s.ml_ai.join(', ')}

MLOps: ${s.mlops.join(', ')}

Infrastructure: ${s.infrastructure.join(', ')}

Web: ${s.web.join(', ')}

---
Other sections:
- https://brysontang.com/?agent=true&content=profile
- https://brysontang.com/?agent=true&content=resume
- https://brysontang.com/?agent=true&content=projects
- https://brysontang.com/?agent=true&content=contact
`;
}

// Generate contact content
function generateContact() {
  const p = AGENT_DATA.profile;
  return `BRYSON TANG - CONTACT
=====================

Email: ${p.contact.email}
Phone: ${p.contact.phone}
LinkedIn: ${p.links.linkedin}
GitHub: ${p.links.github}
Website: ${p.links.website}

MCP Endpoint: ${p.links.mcp}
(For AI agents: query structured data via MCP protocol)

Current Status: ${p.status}
Availability: ${p.availability}

---
Other sections:
- https://brysontang.com/?agent=true&content=profile
- https://brysontang.com/?agent=true&content=resume
- https://brysontang.com/?agent=true&content=projects
- https://brysontang.com/?agent=true&content=skills
`;
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const isAgentMode = url.searchParams.get('agent') === 'true';

  // If not agent mode, pass through to static site
  if (!isAgentMode) {
    return context.next();
  }

  // Agent mode - determine content type
  const content = url.searchParams.get('content');

  let responseText;
  let contentType = 'text/plain; charset=utf-8';

  switch (content) {
    case 'profile':
      responseText = generateProfile();
      break;
    case 'resume':
      responseText = generateResume();
      break;
    case 'projects':
      responseText = generateProjects();
      break;
    case 'skills':
      responseText = generateSkills();
      break;
    case 'contact':
      responseText = generateContact();
      break;
    default:
      // Navigation page
      responseText = generateNavigation();
      contentType = 'text/html; charset=utf-8';
  }

  return new Response(responseText, {
    headers: {
      'Content-Type': contentType,
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
